name: Jeb's Co.
favicon: null
layout_spectrum: 0.4718721106182784
typography_spectrum: 0.9482592907734215
title: Jeb's Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0b07'
    - '#586a92'
    - '#7c9cc2'
    - '#edd0b0'
    - '#d61f00'
  brandStrength: 0.21156558045186102
  lightness: 0.7437687399797142
  saturation: 0.03578066034242511
  rhythmicContrast: 0.07646136055700481
purpose: []
