name: Jeb's Co.
favicon: null
layout_spectrum: 0.4718721106182784
typography_spectrum: 0.9482592907734215
title: Jeb's Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.21156558045186102
  lightness: 0.7437687399797142
  saturation: 0.03578066034242511
  rhythmicContrast: 0.07646136055700481
purpose: []
